name: cui_timetable
version: 1.0.0+1
publish_to: none
description: Build with â¤ for specially IOS Platform.
environment:
  sdk: ">=2.16.1 <3.0.1"

dependencies:
  animated_text_kit: ^4.2.1
  auto_size_text: ^3.0.0
  awesome_extensions: ^2.0.2
  awesome_notifications: ^0.7.4+1
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.0.3
  connectivity_plus: ^3.0.2
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  dart_date: ^1.1.1
  device_preview: ^1.1.0
  firebase_analytics: ^10.0.3
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_database: ^10.0.3
  firebase_messaging: ^14.0.3
  firebase_remote_config: ^3.0.3
  firebase_storage: ^11.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.3
  flutter_slidable: ^2.0.0
  flutter_soul:
    git:
      url: https://github.com/ahmadbintariq4u/flutter_soul.git
      ref: main
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.2.1
  get: ^4.6.3
  google_fonts: ^3.0.0
  google_sign_in: ^5.4.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  jiffy: ^5.0.0
  logger: ^1.1.0
  particles_flutter: ^0.1.4
  path_provider: ^2.0.9
  rive: ^0.9.1
  sqflite: ^2.0.2+1
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.1.5
  flutter_test:
    sdk: flutter
  # objectbox_generator: ^1.5.0
  hive_generator: ^2.0.0

flutter_native_splash:
  color: "#d4dfed"
  image: assets/splash.png
  android_12:
    image: assets/splash12.png
    icon_background_color_dark: "#d4dfed"
    # color: '#d4dfed'
  android: true
  ios: true
  web: true
  fullscreen: true

flutter_icons:
  android: false
  ios: true
  image_path: assets/icon.png
  # adaptive_icon_background: '#93afd2'
  # adaptive_icon_foreground: 'assets/icon_foreground.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/drawer/
    - assets/about_us/
    - assets/timetable/
    - assets/home/
    - assets/freerooms/
    - assets/misc/
    - assets/sign_in/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Regular.ttf
style: normal
weight: 500
